### ISSUE TITLE
chatty bit opening streamers channel. 

### ISSUE THREAD

**Issue by hexdsl** [jp1995/kappa-launcher#1]
Hello

I prefer chatty to chatterino but it doesn't automatically open atreamers channel when I launch it. Do I need to add extra arguments or is this not supported as expected?

**Comment by jp1995** [comment]
I've never used chatty, other than to make sure the basic functionality is there with respect to the script. But a quick search suggests this is possible with -channel <channel>

More launch options: http://chatty.github.io/help/help.html#launch
