### ISSUE TITLE
non western streams dont play

### ISSUE THREAD

**Issue by jasondaigo** [jp1995/kappa-launcher#13]
kpl is working good but if i wanna watch any asian streamer it doesnt play.
` kpl
Configuration file found, proceeding
json file successfully populated
launching streamlink
[cli][info] Found matching plugin twitch for URL twitch.tv/肉乙
ERROR: Chat not defined in config file
[jason@behemoth downloads]$ error: Unable to validate JSON: Unable to validate key 'data': Unable to validate key 'streamPlaybackAccessToken': Type of None should be 'dict' but is 'NoneType' or Key 'videoPlaybackAccessToken' not found in {'streamPlaybackAccessToken': None}
`
it maybe occures because even though these streamers have valid urls in browsers, in kpl the asian name is used?

you can see it on this streamers for example: https://www.twitch.tv/zoe_0601, https://www.twitch.tv/rubyteacher, https://www.twitch.tv/sungminhue

**Comment by jp1995** [comment]
Interesting issue.

The API gives two separate name values, `display_name` and `name`. The former is used below the stream, and can be any script / encoding. Until now, kpl has been using the `display_name` value. This is not ideal. 

Fixed in  ed693d955dcffadfac746ba8d2eca6f09d32545c

**Comment by jasondaigo** [comment]
i think this made a comeback in the current version;  cannot play korean or japanese streams with kpl

**Comment by jp1995** [comment]
Right... The values changed from `display_name` and `name` to `user_name` and `login_name` respectively. Thank you Twitch.

fixed, [14e0dd6](https://github.com/jp1995/kappa-launcher/commit/14e0dd6fb44c77d5e7eceb702aa48dffbed69ad5)
