### ISSUE TITLE
after twitch api change no cannel listed anymore

### ISSUE THREAD

**Issue by jasondaigo** [jp1995/kappa-launcher#15]
delete old config and started new one with another token. all i see in terminal iis this:    
jq: error (at /home/jason/.config/kpl/followdata.json:0): Cannot iterate over null (null)

and rofi channel list is empty

**Comment by jp1995** [comment]
duh, I was gonna do something about this but then I forgot..

fixing the API should be easy, the transition documentation is pretty clear. I'll deal with it tomorrow.

**Comment by jasondaigo** [comment]
thanks sir.     
didnt change a thing on my side though, using aur/kappa-launcher-git r90.8b76f12-1 [installed] [2+] [1.60%] [2 Mar 2022     

started from scratch, still no channels and the error jq: error (at /home/jason/.config/kpl/followdata.json:0): Cannot iterate over null (null)

**Comment by jp1995** [comment]
Hmm, seems to work just fine for me

The jq issue indicates that it's failed to query any useful data. Are you getting any other errors? Did you regenerate your auth token?

**Comment by jasondaigo** [comment]
> Hmm, seems to work just fine for me
> 
> The jq issue indicates that it's failed to query any useful data. Are you getting any other errors? Did you regenerate your auth token?

new token generated. 

cat followdata.json 
{"error":"Unauthorized","status":401,"message":"Missing scope: user:read:follows"}[jason@behemoth kpl]$

**Comment by jp1995** [comment]
Weird. Are you getting it here? https://spheroid.xyz/kappa/

**Comment by jasondaigo** [comment]
> Weird. Are you getting it here? https://spheroid.xyz/kappa/

yes

**Comment by jp1995** [comment]
Could be cache shenanigans. Works fine for me, and if you look at the generation closer it does include the scope.

**Comment by jp1995** [comment]
no worries!
